import Head from "next/head";
import Image from "next/image";
import joystick from "../public/images/joystick.jpg";
import work from "../public/images/work.jpg";
import self from "../public/images/self.jpg";
import study from "../public/images/study.jpg";
import exercise from "../public/images/exercise.jpg";
import social from "../public/images/social.jpg";
import play from "../public/images/play.jpg";
import jerry from "../public/images/jerry.jpg";
import Cards from "../components/cards";
import Profile from "../components/profile";
export default function Home() {
  return (
    <div className="h-fit md:h-screen  md:flex-col flex flex-row justify-center items-center ">
      <Head>
        <title>Health app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main div */}
      <div className="lg:w-2/4 w-11/12 flex flex-col gap-7   lg:flex-row">
        <div className="">
          <Profile />
        </div>
        {/*second div */}
        <div className="grid  grid-cols-1 gap-7  w-full h-full  md:grid-cols-3">
          {/* this is 6 grid    */}
          {/* 1 */}
          <Cards />
          {/* 6 */}
        </div>
      </div>
    </div>
  );
}
